"""Create GitHub issue from a security finding."""
import json
import urllib.request

def github_issue(finding_json: str, repo: str = "", token: str = "", labels: str = "security,vulnerability") -> str:
    try:
        finding = json.loads(finding_json) if isinstance(finding_json, str) else finding_json
    except Exception:
        return json.dumps({"error": "Invalid finding JSON"}, indent=2)

    if not repo or not token:
        return json.dumps({
            "error": "Missing required parameters",
            "required": ["repo (owner/repo format)", "token (GitHub personal access token)"],
            "hint": "Create token at https://github.com/settings/tokens with 'repo' scope"
        }, indent=2)

    sev = finding.get("severity", "medium").lower()
    title_finding = finding.get("title", finding.get("type", "Security Finding"))
    target = finding.get("target", finding.get("host", ""))
    evidence = finding.get("evidence", finding.get("response", ""))
    remediation = finding.get("remediation", finding.get("fix", "See vulnerability details"))

    sev_emoji = {"critical": "🔴", "high": "🟠", "medium": "🟡", "low": "🟢", "info": "🔵"}.get(sev, "⚪")

    body = f"""## {sev_emoji} Security Vulnerability — {title_finding}

### Summary
| Field | Value |
|-------|-------|
| **Severity** | {sev.upper()} |
| **Target** | {target} |
| **Type** | {finding.get('type', finding.get('vuln_type', 'Unknown'))} |
| **Status** | {finding.get('status', 'new')} |
| **Detected by** | Cybersec MCP |

### Evidence
```
{evidence[:3000]}
```

### Remediation
{remediation}

### Metadata
- Finding ID: {finding.get('id', finding.get('finding_id', 'N/A'))}
- CVSS: {finding.get('cvss', 'N/A')}
- Detected: {finding.get('detected_at', finding.get('added', 'N/A'))}

---
*This issue was auto-generated by Cybersec MCP. Do not edit the metadata block above.*
"""

    label_list = [l.strip() for l in labels.split(",")] + [f"severity:{sev}"]

    payload = {
        "title": f"[{sev.upper()}] {title_finding} — {target}",
        "body": body,
        "labels": label_list[:10],
    }

    api_url = f"https://api.github.com/repos/{repo}/issues"
    headers = {
        "Content-Type": "application/json",
        "Authorization": f"token {token}",
        "Accept": "application/vnd.github.v3+json",
    }

    try:
        data = json.dumps(payload).encode("utf-8")
        req = urllib.request.Request(api_url, data=data, headers=headers, method="POST")
        resp = urllib.request.urlopen(req, timeout=15)
        body = json.loads(resp.read().decode("utf-8"))
        return json.dumps({
            "status": "created",
            "issue_number": body.get("number"),
            "issue_url": body.get("html_url"),
            "labels": label_list,
            "repository": repo,
        }, indent=2)
    except urllib.error.HTTPError as e:
        err_body = e.read().decode("utf-8", errors="ignore")
        return json.dumps({
            "error": f"GitHub API returned {e.code}",
            "response": json.loads(err_body).get("message", err_body)[:300] if err_body else "",
        }, indent=2)
    except Exception as e:
        return json.dumps({"error": str(e)}, indent=2)