"""Penetration testing report generator."""

from datetime import datetime

def gen_report(target: str, findings: dict, format: str = "markdown") -> str:
    """Generate pentest report from findings."""
    if format == "markdown":
        return _gen_markdown(target, findings)
    elif format == "json":
        import json
        return json.dumps(findings, indent=2)
    return str(findings)

def _gen_markdown(target: str, findings: dict) -> str:
    lines = []
    lines.append(f"# Penetration Test Report: {target}")
    lines.append(f"**Date:** {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    lines.append(f"**Tool:** Cybersec Plugin for OpenCode")
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    open_ports = findings.get("open_ports", [])
    vulns = findings.get("vulnerabilities", [])
    lines.append(f"- **Open Ports Found:** {len(open_ports)}")
    lines.append(f"- **Vulnerabilities Found:** {len(vulns)}")
    if findings.get("technologies"):
        lines.append(f"- **Technologies:** {', '.join(findings['technologies'][:5])}")
    lines.append("")
    if open_ports:
        lines.append("## Open Ports")
        lines.append("")
        lines.append("| Port | Service | Banner |")
        lines.append("|------|---------|--------|")
        for p in open_ports:
            svc = p.get("service", "unknown")
            banner = p.get("banner", "")[:50]
            lines.append(f"| {p.get('port', '?')} | {svc} | {banner} |")
        lines.append("")
    if vulns:
        lines.append("## Vulnerabilities")
        lines.append("")
        lines.append("| ID | Severity | Description |")
        lines.append("|----|----------|-------------|")
        for v in vulns:
            lines.append(f"| {v.get('id', 'N/A')} | {v.get('severity', 'UNKNOWN')} | {v.get('description', '')[:100]} |")
        lines.append("")
    lines.append("## Recommendations")
    lines.append("")
    if vulns:
        for v in vulns:
            lines.append(f"- **{v.get('id', 'N/A')}:** Update/patch to fix {v.get('description', '')[:50]}")
    else:
        lines.append("- No critical issues identified in this assessment.")
    lines.append("")
    lines.append("---")
    lines.append(f"*Report generated by Cybersec Plugin on {datetime.now().isoformat()}*")
    return "\n".join(lines)
